name: reward

on:
  push:
    paths:
      - 'reward.py'
      - '.github/workflows/reward.yml'
      - 'requirements.txt'
  schedule:
    - cron: 0,30 * * * *
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cat requirements.txt | xargs -n 1 pip install
          touch /tmp/continue
      - name: Set proxy
        uses: w311ang/setproxy@main
        with:
          config: ${{ secrets.ss_config }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: itchat.pkl
          key: build-${{ github.run_id }}
          restore-keys: |
            build-
      - name: SSH connection to Actions
        if: github.event.inputs.ssh == 'true'
        uses: P3TERX/ssh2actions@v1.0.0
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      - name: Run
        run: |
          proxychains python -u reward.py > qrcode.txt
