name: signin

on:
  push:
    branches: [ main ]
    paths:
      - '*.py'
      - '.github/workflows/signin.yml'
      - 'requirements.txt'
#  watch:
#    types: started
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cat requirements.txt | xargs -n 1 pip install
    - name: Set proxy
      uses: w311ang/setproxy@main
      with:
        config: ${{ secrets.ss_config }}
    - name: Cache
      uses: actions/cache@v2
      with:
        path: itchat.pkl
        key: build-${{ github.run_id }}
        restore-keys: |
          build-
    - name: Run
      env:
        name: ${{ secrets.realname }}
      run: |
        proxychains python -u signin.py
